### ISSUE TITLE
string-to-curve should be injective (for valid inputs)

### ISSUE THREAD

**Issue by algoradam** [pairingwg/BLS_standard_wg#12]
As currently specified, string-to-curve can interpret different strings as the same curve point:
- Any string whose first bit is 1 is interpreted as the point at infinity. Instead string-to-curve should reject any strings with first bit 1 other than 1000...0
- Because of the padding rules, a string with leading/trailing zero bytes can have those bytes removed and still decode to the same point, as steps 1 and 2 of string_to_curve will add these zero bytes back. Instead string-to-curve should require its input string have fixed length and check that all padding bits are zero.

**Comment by kwantam** [comment]
Thanks for the comment.

We probably won't specify serialization formats in this draft; ideally, that's part of the underlying curve's specification. For BLS12-381 in the reference implementations we'll probably use ZCash's serialization format or something similar (see #16).

So it looks to me like we can safely close this issue. If I've misunderstood your comment or if something seems wrong, please reopen and let me know!
