### ISSUE TITLE
Integrated prehashing 

### ISSUE THREAD

**Issue by burdges** [pairingwg/BLS_standard_wg#18]
BLS signatures should support stronger aggregation optimizations, ala https://github.com/w3f/bls/blob/master/src/verifiers.rs#L72

In practice, messages would be used as hash maps keys when doing this, but actual messages can get large, so they should not be hashed twice.  You should use messages not curve points here because hash-to-curve functions output projective points, not affine ones.

I think the fastest solution is to hash messages with Blake2b/x, produce a single ChaCha state, which then acts as the hash map key being rehashed with randomness using SipHasher or whatever.  This requires standardizing this opening up of the internals of Blake2b/x, which sucks.  In practice, you might do this by adapting Mike Hamburg's STROBE construction for Keccak to ChaCha, for the smaller state size, maybe attempting to retain some shred of Blake2b/x compatibility.  This sucks even more.

Instead, one should just hash real messages down into 32 byte "messages" that both the hash maps and the real hash-to-curve function take.  This double hashing slightly slows down very simple BLS implementations, but not so that anybody notices.  This "integrated prehashing" version is generic over the hash function.  You could even specify that implementations may require messages to be 32 bytes.

**Comment by kwantam** [comment]
It's not totally obvious to me, but I *think* the version of hash_to_field specified in the [current spec](https://github.com/pairingwg/bls_standard/blob/master/minutes/spec-v1.md) already makes it possible to avoid double hashing, without explicitly specifying any kind of "prehash" mode.

Specifically, notice that `msg'` depends on `hash_fn(msg)`. This means that, having hashed `msg` once, one can compute hash_to_field without rehashing (in particular, by writing a function that implements the hash_to_field procedure using a different interface).

Is the above clear? Am I misunderstanding your comment? I agree with you that avoiding inefficiencies in hashing long messages is important---thank you for bringing this up!

EDIT: also, as an aside: the current placeholder "ciphersuites" stick to SHA256 for hashing, but that's a (ciphersuite) implementation detail---obviously other suites using other hashes can be defined.

**Comment by burdges** [comment]
Yes, it suffices for `hash_fn(msg)` produces some small value, like 256 bits, upon which `hash_to_field` operates with additional hashing.  Thanks!
